services:
  db1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    hostname: db1
    container_name: db1
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pcuong@2411"
      MSSQL_PID: "Developer"
      MSSQL_LCID: "1033"
      MSSQL_AGENT_ENABLED: true
      PATH: $PATH:/opt/mssql-tools18/bin
    volumes:
      - db1_data:/var/opt/mssql
    ports:
      - "1434:1433"
    networks:
      - sqlnet

  db2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    hostname: db2
    container_name: db2
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pcuong@2411"
      MSSQL_PID: "Developer"
      MSSQL_LCID: "1033"
      MSSQL_AGENT_ENABLED: true
      PATH: $PATH:/opt/mssql-tools18/bin
    volumes:
      - db2_data:/var/opt/mssql
    ports:
      - "1435:1433"
    networks:
      - sqlnet

  db3:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    hostname: db3
    container_name: db3
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pcuong@2411"
      MSSQL_PID: "Developer"
      MSSQL_LCID: "1033"
      MSSQL_AGENT_ENABLED: true
      PATH: $PATH:/opt/mssql-tools18/bin
    volumes:
      - db3_data:/var/opt/mssql
    ports:
      - "1436:1433"
    networks:
      - sqlnet

volumes:
  db1_data:
  db2_data:
  db3_data:

networks:
  sqlnet:
    driver: bridge